# Generated by Django 5.1.1 on 2024-10-08 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YandexAccount',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=250, unique=True)),
                ('default_email', models.EmailField(max_length=250)),
                ('first_name', models.CharField(blank=True, default='', max_length=250)),
                ('last_name', models.CharField(blank=True, default='', max_length=250)),
                ('avatar_id', models.CharField(default='0/0-0', max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yandex account',
                'verbose_name_plural': 'Yandex accounts',
            },
        ),
    ]
