# Generated by Django 5.1.1 on 2024-10-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yandex', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yandexaccount',
            old_name='default_email',
            new_name='email',
        ),
    ]
